version: "3.8"

services:
  mailserver:
    build:
      context: ./docker/mailserver
    hostname: "127.0.0.1"
    container_name: mailserver
    environment:
      ENABLE_SPAMASSASSIN: ${MAILSERVER_ENABLE_SPAMASSASSIN:-1}
      ENABLE_CLAMAV: ${MAILSERVER_ENABLE_CLAMAV:-1}
      ENABLE_FAIL2BAN: ${MAILSERVER_ENABLE_FAIL2BAN:-1}
      ENABLE_POSTGREY: ${MAILSERVER_ENABLE_POSTGREY:-0}
      ONE_DIR: ${MAILSERVER_ONE_DIR:-1}
      DMS_DEBUG: ${MAILSERVER_DMS_DEBUG:-0}
      SSH_ROOT_PASSWORD: ${POSTFIX_SSH_ROOT_PASSWORD:-root}
    volumes:
      - ./docker/mailserver/maildata:/var/mail # Mail data
      - ./docker/mailserver/config/:/tmp/docker-mailserver # Mailserver configuration
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993" # You can change external port to avoid conflict
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  roundcube:
    image: roundcube/roundcubemail:1.6.x-apache
    container_name: roundcube
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: ${ROUNDCUBEMAIL_DEFAULT_HOST:-mailserver}
      ROUNDCUBEMAIL_SMTP_SERVER: ${ROUNDCUBEMAIL_SMTP_SERVER:-mailserver}
      ROUNDCUBEMAIL_SMTP_PORT: ${ROUNDCUBEMAIL_SMTP_PORT:-587}
      ROUNDCUBEMAIL_DEFAULT_PORT: ${ROUNDCUBEMAIL_DEFAULT_PORT:-143}
      ROUNDCUBEMAIL_REQUEST_PATH: ${ROUNDCUBEMAIL_REQUEST_PATH:-/roundcube/}
    volumes:
      - ./docker/roundcube/data:/var/roundcube/data # Data
      - ./docker/roundcube/logs:/var/roundcube/logs # Logs
      - ./docker/roundcube/config:/var/roundcube/config # Config
      - ./docker/roundcube/RoundcubeAutoLogin.php:/var/www/html/RoundcubeAutoLogin.php
    restart: unless-stopped

  admin_panel:
    container_name: webmail-admin
    build:
      context: .
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      ROUNDCUBE_ENABLE: ${ROUNDCUBE_ENABLE}
      ROUNDCUBE_URL: ${ROUNDCUBE_URL:-"http://roundcube"}
      ROUNDCUBE_LOGIN_URL: ${ROUNDCUBE_LOGIN_URL:-"/roundcube/RoundcubeAutoLogin.php"}
      POSTFIX_SSH_ROOT_PASSWORD: ${POSTFIX_SSH_ROOT_PASSWORD:-root}
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  maildata:
  roundcube_data:
  roundcube_logs:
  roundcube_config:
